'use client';

import { useEffect, useState, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import { SessionSummary } from '@/types/session';
import { supabaseBrowser } from '@/services/supabase/client';

type ViewState = 'loading' | 'generating' | 'ready' | 'error' | 'no-access';

interface SummarySection {
  icon:     string;
  title:    string;
  color:    string;
  children: React.ReactNode;
}

function Card({ icon, title, color, children }: SummarySection) {
  return (
    <div className="bg-surface-1 border border-surface-3 rounded-2xl p-6">
      <div className={`flex items-center gap-2 mb-4 ${color}`}>
        <span className="text-lg">{icon}</span>
        <h3 className="font-semibold text-sm uppercase tracking-wide">{title}</h3>
      </div>
      {children}
    </div>
  );
}

function Chip({ text }: { text: string }) {
  return (
    <span className="inline-block bg-surface-2 border border-surface-3 text-slate-300 text-xs px-3 py-1 rounded-full">
      {text}
    </span>
  );
}

export default function SummaryView({ sessionId, appUserId }: { sessionId: string; appUserId: string }) {
  const router = useRouter();
  const [viewState, setViewState] = useState<ViewState>('loading');
  const [summary,   setSummary]   = useState<SessionSummary | null>(null);
  const [isTeacher, setIsTeacher] = useState(false);
  const [error,     setError]     = useState('');

  const fetchExistingSummary = useCallback(async () => {
    if (!appUserId) return { data: null, teacher: false };

    const { data: pData } = await supabaseBrowser
      .from('participants')
      .select('role')
      .eq('session_id', sessionId)
      .eq('app_user_id', appUserId)
      .single();

    const teacher = pData?.role === 'teacher';
    setIsTeacher(teacher);

    const { data } = await supabaseBrowser
      .from('session_summaries')
      .select('*')
      .eq('session_id', sessionId)
      .maybeSingle();

    return { data: data as SessionSummary | null, teacher };
  }, [sessionId, appUserId]);

  const generateSummary = useCallback(async () => {
    setViewState('generating');
    setError('');
    try {
      const res = await fetch('/api/summary', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'x-user-id': appUserId },
        body: JSON.stringify({ sessionId }),
      });
      const json = await res.json();
      if (!json.success) throw new Error(json.error.message);
      setSummary(json.data.summary as SessionSummary);
      setViewState('ready');
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : String(err));
      setViewState('error');
    }
  }, [sessionId, appUserId]);

  useEffect(() => {
    if (!appUserId) return; // Wait for appUserId to be loaded from localStorage

    (async () => {
      const { data: existing, teacher } = await fetchExistingSummary();
      if (existing) {
        setSummary(existing);
        setViewState('ready');
      } else if (teacher) {
        // Auto-generate if teacher and no summary exists yet
        await generateSummary();
      } else {
        // Students don't have access to GENERATE it, but they can view it if it exists.
        setViewState('no-access');
      }
    })();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [appUserId, sessionId]);

  const BackButton = () => (
    <button
      onClick={() => router.push('/')}
      className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white transition-colors"
    >
      <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
      </svg>
      Back to Home
    </button>
  );

  if (viewState === 'loading' || viewState === 'generating') {
    return (
      <div className="min-h-screen bg-surface-0 flex flex-col items-center justify-center gap-4 text-white">
        <div className="w-10 h-10 border-2 border-aria-purple border-t-transparent rounded-full animate-spin" />
        <p className="text-slate-400 text-sm">
          {viewState === 'generating' ? 'Generating your session summary with ARIA…' : 'Loading summary…'}
        </p>
        <p className="text-slate-600 text-xs">This may take 10–20 seconds</p>
      </div>
    );
  }

  if (viewState === 'no-access') {
    return (
      <div className="min-h-screen bg-surface-0 flex items-center justify-center p-6 text-white">
        <div className="text-center max-w-sm">
          <p className="text-slate-400 mb-6 text-sm">The session summary hasn&apos;t been generated by the instructor yet. Please check back later!</p>
          <BackButton />
        </div>
      </div>
    );
  }

  if (viewState === 'error' || !summary) {
    return (
      <div className="min-h-screen bg-surface-0 flex items-center justify-center p-6 text-white">
        <div className="bg-surface-1 border border-surface-3 rounded-2xl p-8 max-w-sm w-full text-center space-y-4">
          <div className="text-live-red text-4xl">⚠</div>
          <h2 className="text-lg font-bold">Summary generation failed</h2>
          {error && <p className="text-slate-400 text-sm">{error}</p>}
          <div className="flex flex-col gap-2">
            {isTeacher && (
              <button
                onClick={generateSummary}
                className="w-full py-2.5 bg-aria-purple hover:bg-aria-purple/80 text-white rounded-xl text-sm font-semibold transition-colors"
              >
                Retry Summary
              </button>
            )}
            <BackButton />
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-surface-0 text-white">
      <div className="max-w-4xl mx-auto px-4 py-10 space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between flex-wrap gap-4">
          <div>
            <p className="text-slate-500 text-xs font-semibold uppercase tracking-widest mb-1">Session complete</p>
            <h1 className="text-3xl font-black tracking-tight">Class Summary</h1>
          </div>
          <div className="flex items-center gap-3">
            {isTeacher && (
              <button
                onClick={generateSummary}
                className="text-xs text-slate-400 hover:text-white border border-surface-3 hover:border-slate-500 px-3 py-2 rounded-xl transition-colors"
              >
                Regenerate
              </button>
            )}
            <button
              onClick={() => router.push('/')}
              className="px-4 py-2 bg-aria-purple hover:bg-aria-purple/80 text-white rounded-xl text-sm font-semibold transition-colors"
            >
              Back to Home
            </button>
          </div>
        </div>

        {/* ARIA interventions badge */}
        <div className="inline-flex items-center gap-2 bg-aria-purple/10 border border-aria-purple/20 rounded-full px-4 py-2">
          <span className="text-aria-purple-light font-bold text-lg">{summary.aria_interventions_count ?? 0}</span>
          <span className="text-aria-purple-light text-sm">ARIA interventions during this session</span>
        </div>

        {/* Overview */}
        {summary.overview && (
          <Card icon="📋" title="Overview" color="text-slate-300">
            <p className="text-slate-300 text-sm leading-relaxed">{summary.overview}</p>
          </Card>
        )}

        {/* Topics covered */}
        {summary.topics_covered?.length > 0 && (
          <Card icon="📚" title="Topics Covered" color="text-role-teacher">
            <div className="flex flex-wrap gap-2">
              {summary.topics_covered.map((t, i) => <Chip key={i} text={t} />)}
            </div>
          </Card>
        )}

        {/* Learning gaps */}
        {summary.common_learning_gaps?.length > 0 && (
          <Card icon="⚠️" title="Learning Gaps" color="text-warning-amber">
            <div className="space-y-3">
              {summary.common_learning_gaps.map((g, i) => (
                <div key={i} className="bg-surface-2 border border-surface-3 rounded-xl p-4">
                  <p className="font-semibold text-sm text-white mb-1">{g.concept}</p>
                  <p className="text-xs text-slate-400 mb-2 leading-relaxed">{g.description}</p>
                  {g.affectedStudents?.length > 0 && (
                    <div className="flex flex-wrap gap-1 mb-2">
                      {g.affectedStudents.map((s, j) => (
                        <span key={j} className="text-[10px] bg-live-red/10 border border-live-red/20 text-live-red px-2 py-0.5 rounded-full">{s}</span>
                      ))}
                    </div>
                  )}
                  <p className="text-xs text-connected-green leading-relaxed">
                    <span className="font-semibold">Recommendation: </span>{g.recommendation}
                  </p>
                </div>
              ))}
            </div>
          </Card>
        )}

        {/* Student insights */}
        {summary.student_insights?.length > 0 && (
          <Card icon="👤" title="Student Insights" color="text-role-student">
            <div className="space-y-3">
              {summary.student_insights.map((s, i) => (
                <div key={i} className="bg-surface-2 border border-surface-3 rounded-xl p-4">
                  <p className="font-semibold text-sm text-white mb-2">{s.studentName}</p>
                  {s.strengths?.length > 0 && (
                    <div className="mb-2">
                      <p className="text-[10px] font-semibold text-connected-green uppercase tracking-wide mb-1">Strengths</p>
                      <ul className="space-y-0.5">
                        {s.strengths.map((str, j) => (
                          <li key={j} className="text-xs text-slate-300 flex items-start gap-1.5">
                            <span className="text-connected-green mt-0.5">✓</span>{str}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                  {s.needsSupport?.length > 0 && (
                    <div>
                      <p className="text-[10px] font-semibold text-warning-amber uppercase tracking-wide mb-1">Needs Support</p>
                      <ul className="space-y-0.5">
                        {s.needsSupport.map((n, j) => (
                          <li key={j} className="text-xs text-slate-300 flex items-start gap-1.5">
                            <span className="text-warning-amber mt-0.5">→</span>{n}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </Card>
        )}

        {/* Recommendations */}
        {summary.recommendations && (
          <Card icon="💡" title="Recommendations" color="text-aria-purple-light">
            <p className="text-slate-300 text-sm leading-relaxed">{summary.recommendations}</p>
          </Card>
        )}

        {/* Footer */}
        <div className="pt-4 pb-10 text-center">
          <button
            onClick={() => router.push('/')}
            className="px-6 py-3 bg-surface-1 hover:bg-surface-2 border border-surface-3 hover:border-slate-500 text-white rounded-xl text-sm font-semibold transition-colors"
          >
            ← Back to Home
          </button>
        </div>
      </div>
    </div>
  );
}
